[[redirects]]
  from = "/search"
  to = "https://65291f76077da31ba112154d--neon-biscuit-c99656.netlify.app/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"